name: CI Testing

on: push

jobs:
    test:
        name: Run tests (Node v${{ matrix.node-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [10, 12.18, 14]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up node ${{ matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install dependencies
              run: |
                  yarn install

            - name: Run CI tests with coverage
              run: |
                  yarn run test:ci

            - name: Upload code coverage
              uses: codecov/codecov-action@v1
              with:
                  flags: unittests
                  env_vars: ${{ matrix.os }}, ${{ matrix.node-version }}


    build:
        name: Test build (Node v${{ matrix.node-version }}, ${{ matrix.os }})
        needs: test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node-version: [10.x, 12.x, 14.x]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up node ${{ matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install dependencies
              run: |
                  yarn install

            - name: Build app for Github Pages
              run: |
                  yarn run build:gh


