name: Deployment

on:
    workflow_run:
        workflows: ["CI Testing", "CodeQL"]
        branches: [master] # generally, only deploy if we are on 'master'
        types:
            - completed
            - requested

jobs:
    build:
        name: Deploy app (Node v${{ matrix.node-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [12.18]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up node ${{ matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install dependencies
              run: |
                  yarn install

            - name: Build app for GH Pages
              run: |
                  yarn build:gh

            - name: Deploy to GH Pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn run deploy:ci

