name: Deploy app

on:
    push:
        branches:
            - master # generally, only deploy if we are on 'master'

jobs:
    build:
        name: Build app (Node v${{ matrix.node-version }}, ${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [12.18]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up node ${{ matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: yarn install dependencies
              run: |
                  yarn install

            - name: Build app for Github Pages
              run: |
                  yarn run build:gh


    deploy:
        name: Deploy app
        needs: build
        runs-on: ${{ matrix.os }}
            strategy:
                matrix:
                    os: [ubuntu-latest]
                    node-version: [12.18]

        steps:
            - name: deploy message
              run: echo "Hello Gh Pages. This will be deployed"

